'''
famille=["pere","mere","fils","fille"]
print(famille[0])
famille.append("soeur")
print(famille)
famille.pop(0)
print(famille)
'''
ma_liste=[1,2,3,4,5]
ma_liste2=[6,7,8,9,10]
ma_liste3=ma_liste+ma_liste2
print(ma_liste3)
ma_liste3[1]="11"
print(ma_liste3)
